name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Firebase configuration
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "TEST_SECRET=${{ secrets.TEST_SECRET }}" >> $GITHUB_ENV

      - name: Replace secrets in script.js
        run: |
          sed -i "s|%FIREBASE_API_KEY%|$FIREBASE_API_KEY|g" js/script.js
          sed -i "s|%FIREBASE_AUTH_DOMAIN%|$FIREBASE_AUTH_DOMAIN|g" js/script.js
          sed -i "s|%FIREBASE_PROJECT_ID%|$FIREBASE_PROJECT_ID|g" js/script.js
          sed -i "s|%FIREBASE_STORAGE_BUCKET%|$FIREBASE_STORAGE_BUCKET|g" js/script.js
          sed -i "s|%FIREBASE_MESSAGING_SENDER_ID%|$FIREBASE_MESSAGING_SENDER_ID|g" js/script.js
          sed -i "s|%FIREBASE_APP_ID%|$FIREBASE_APP_ID|g" js/script.js
          sed -i "s|%TEST_SECRET%|$TEST_SECRET|g" js/script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: ./
