name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Replace Secrets in Script
      run: |
        sed -i 's/%FIREBASE_API_KEY%/${{ secrets.FIREBASE_API_KEY }}/g' js/script.js
        sed -i 's/%FIREBASE_AUTH_DOMAIN%/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' js/script.js
        sed -i 's/%FIREBASE_PROJECT_ID%/${{ secrets.FIREBASE_PROJECT_ID }}/g' js/script.js
        sed -i 's/%FIREBASE_STORAGE_BUCKET%/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' js/script.js
        sed -i 's/%FIREBASE_MESSAGING_SENDER_ID%/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' js/script.js
        sed -i 's/%FIREBASE_APP_ID%/${{ secrets.FIREBASE_APP_ID }}/g' js/script.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

